config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class="navbar-inverse">
      <ul>
        <li><a href="<%= pages_one_path %>">One</a></li>
        <li><%= link_to 'Two', pages_two_path %></li>
        <li><%= link_to 'Three', pages_three_path %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>CARLOS EDUARDO FUENTEALBA CRUZ</h1>

<p>Proyecto desafio FIRST_APP</p>

app/views/pages/three.html.erb
<h2>Agrega un titulo h2</h2>

<p>lorem ipsum bla ble bli</p>

app/views/pages/two.html.erb
<h1>IMAGEN DE CAPTURA</h1>

<%= image_tag ('RAILS_ROUTE_FirstApp.png')%>